sonar.host.url=http://localhost:9000
sonar.login=sqp_61d66d53000fce919862b72e22619f834faaad28
sonar.projectKey=nextkinlife-backend
sonar.projectName=NextKinLife Backend
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/coverage/**, **/.git/**, **/*.test.js
sonar.scanner.skipJreProvisioning=true
